package com.drivitive.trackanalytics.data.export

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.drivitive.trackanalytics.data.model.ComparisonResult
import java.io.File
import java.time.Duration
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

object HtmlExporter {

    fun exportComparison(context: Context, result: ComparisonResult): Intent {
        val html = generateHtml(result)
        val file = saveToFile(context, html)
        return createShareIntent(context, file)
    }

    private fun generateHtml(result: ComparisonResult): String {
        val timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))

        return """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Track Comparison - ${result.track1.name} vs ${result.track2.name}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            background: #f5f5f5;
            padding: 16px;
        }
        .container { max-width: 800px; margin: 0 auto; }
        h1 {
            color: #1976D2;
            margin-bottom: 8px;
            font-size: 1.5em;
        }
        .timestamp {
            color: #666;
            font-size: 0.875em;
            margin-bottom: 24px;
        }
        .card {
            background: white;
            border-radius: 12px;
            padding: 16px;
            margin-bottom: 16px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .card-title {
            font-size: 1.1em;
            font-weight: 600;
            margin-bottom: 12px;
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px 12px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }
        th {
            font-weight: 500;
            color: #666;
        }
        .track1 { color: #2196F3; font-weight: 500; }
        .track2 { color: #F44336; font-weight: 500; }
        .header-row th:nth-child(2) { color: #2196F3; }
        .header-row th:nth-child(3) { color: #F44336; }
        .progress-container {
            margin: 8px 0;
        }
        .progress-label {
            display: flex;
            justify-content: space-between;
            margin-bottom: 4px;
            font-size: 0.875em;
        }
        .progress-bar {
            height: 8px;
            background: #e0e0e0;
            border-radius: 4px;
            overflow: hidden;
        }
        .progress-fill {
            height: 100%;
            border-radius: 4px;
        }
        .progress-fill.track1 { background: #2196F3; }
        .progress-fill.track2 { background: #F44336; }
        .footer {
            text-align: center;
            color: #999;
            font-size: 0.75em;
            margin-top: 24px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Track Comparison</h1>
        <p class="timestamp">Generated: $timestamp</p>

        <div class="card">
            <div class="card-title">Tracks</div>
            <table>
                <tr class="header-row">
                    <th></th>
                    <th>${result.track1.name}</th>
                    <th>${result.track2.name}</th>
                </tr>
            </table>
        </div>

        <div class="card">
            <div class="card-title">Distance</div>
            <table>
                <tr class="header-row">
                    <th>Metric</th>
                    <th class="track1">${result.track1.name}</th>
                    <th class="track2">${result.track2.name}</th>
                </tr>
                <tr>
                    <td>Distance</td>
                    <td>${formatDistance(result.metrics1.totalDistanceKm)} km</td>
                    <td>${formatDistance(result.metrics2.totalDistanceKm)} km</td>
                </tr>
                <tr>
                    <td>Points</td>
                    <td>${result.metrics1.pointCount}</td>
                    <td>${result.metrics2.pointCount}</td>
                </tr>
            </table>
        </div>

        ${generateElevationCard(result)}
        ${generateSpeedCard(result)}
        ${generateOverlapCard(result)}

        <div class="footer">
            Generated by Track Analytics
        </div>
    </div>
</body>
</html>
        """.trimIndent()
    }

    private fun generateElevationCard(result: ComparisonResult): String {
        val ele1 = result.metrics1.elevation ?: return ""
        val ele2 = result.metrics2.elevation ?: return ""

        return """
        <div class="card">
            <div class="card-title">Elevation</div>
            <table>
                <tr class="header-row">
                    <th>Metric</th>
                    <th class="track1">${result.track1.name}</th>
                    <th class="track2">${result.track2.name}</th>
                </tr>
                <tr>
                    <td>Min elevation</td>
                    <td>${ele1.minElevation.toInt()} m</td>
                    <td>${ele2.minElevation.toInt()} m</td>
                </tr>
                <tr>
                    <td>Max elevation</td>
                    <td>${ele1.maxElevation.toInt()} m</td>
                    <td>${ele2.maxElevation.toInt()} m</td>
                </tr>
                <tr>
                    <td>Elevation range</td>
                    <td>${ele1.elevationRange.toInt()} m</td>
                    <td>${ele2.elevationRange.toInt()} m</td>
                </tr>
                <tr>
                    <td>Total ascent</td>
                    <td>${ele1.totalAscent.toInt()} m</td>
                    <td>${ele2.totalAscent.toInt()} m</td>
                </tr>
                <tr>
                    <td>Total descent</td>
                    <td>${ele1.totalDescent.toInt()} m</td>
                    <td>${ele2.totalDescent.toInt()} m</td>
                </tr>
            </table>
        </div>
        """
    }

    private fun generateSpeedCard(result: ComparisonResult): String {
        val spd1 = result.metrics1.speed ?: return ""
        val spd2 = result.metrics2.speed ?: return ""

        return """
        <div class="card">
            <div class="card-title">Speed & Time</div>
            <table>
                <tr class="header-row">
                    <th>Metric</th>
                    <th class="track1">${result.track1.name}</th>
                    <th class="track2">${result.track2.name}</th>
                </tr>
                <tr>
                    <td>Duration</td>
                    <td>${formatDuration(spd1.duration)}</td>
                    <td>${formatDuration(spd2.duration)}</td>
                </tr>
                <tr>
                    <td>Moving time</td>
                    <td>${formatDuration(spd1.movingTime)}</td>
                    <td>${formatDuration(spd2.movingTime)}</td>
                </tr>
                <tr>
                    <td>Average speed</td>
                    <td>${formatSpeed(spd1.avgSpeedKmh)} km/h</td>
                    <td>${formatSpeed(spd2.avgSpeedKmh)} km/h</td>
                </tr>
                <tr>
                    <td>Avg moving speed</td>
                    <td>${formatSpeed(spd1.avgMovingSpeedKmh)} km/h</td>
                    <td>${formatSpeed(spd2.avgMovingSpeedKmh)} km/h</td>
                </tr>
                <tr>
                    <td>Max speed</td>
                    <td>${formatSpeed(spd1.maxSpeedKmh)} km/h</td>
                    <td>${formatSpeed(spd2.maxSpeedKmh)} km/h</td>
                </tr>
            </table>
        </div>
        """
    }

    private fun generateOverlapCard(result: ComparisonResult): String {
        val overlap = result.overlap

        return """
        <div class="card">
            <div class="card-title">Route Overlap</div>

            <div class="progress-container">
                <div class="progress-label">
                    <span class="track1">${result.track1.name} overlap</span>
                    <span>${formatPercent(overlap.track1OverlapPercent)}%</span>
                </div>
                <div class="progress-bar">
                    <div class="progress-fill track1" style="width: ${overlap.track1OverlapPercent.coerceIn(0.0, 100.0)}%"></div>
                </div>
            </div>

            <div class="progress-container">
                <div class="progress-label">
                    <span class="track2">${result.track2.name} overlap</span>
                    <span>${formatPercent(overlap.track2OverlapPercent)}%</span>
                </div>
                <div class="progress-bar">
                    <div class="progress-fill track2" style="width: ${overlap.track2OverlapPercent.coerceIn(0.0, 100.0)}%"></div>
                </div>
            </div>

            <table style="margin-top: 16px;">
                <tr>
                    <td>Shared distance</td>
                    <td>${formatDistance(overlap.sharedDistanceKm)} km</td>
                </tr>
                <tr>
                    <td>${result.track1.name} unique</td>
                    <td>${formatDistance(overlap.track1UniqueKm)} km</td>
                </tr>
                <tr>
                    <td>${result.track2.name} unique</td>
                    <td>${formatDistance(overlap.track2UniqueKm)} km</td>
                </tr>
            </table>
        </div>
        """
    }

    private fun saveToFile(context: Context, html: String): File {
        val timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"))
        val filename = "track_comparison_$timestamp.html"
        val file = File(context.cacheDir, filename)
        file.writeText(html)
        return file
    }

    private fun createShareIntent(context: Context, file: File): Intent {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )

        return Intent(Intent.ACTION_SEND).apply {
            type = "text/html"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "Track Comparison")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
    }

    private fun formatDistance(km: Double): String = "%.2f".format(km)
    private fun formatSpeed(kmh: Double): String = "%.1f".format(kmh)
    private fun formatPercent(pct: Double): String = "%.1f".format(pct)

    private fun formatDuration(duration: Duration): String {
        val hours = duration.toHours()
        val minutes = duration.toMinutesPart()
        val seconds = duration.toSecondsPart()

        return when {
            hours > 0 -> "${hours}h ${minutes}m ${seconds}s"
            minutes > 0 -> "${minutes}m ${seconds}s"
            else -> "${seconds}s"
        }
    }
}
